service: cowsay
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  lambdaHashingVersion: "20201221"

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
