# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: bespinian
service: cowsay

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  lambdaHashingVersion: "20201221"

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
