name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    environment: aws-development
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - run: npm ci
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
